### ISSUE TITLE
Incompatible with IDE build 2022.3 EAP

### ISSUE THREAD

**Issue by victor-falcon** [youngstead/idea-relative-line-numbers#1]
![image](https://user-images.githubusercontent.com/238766/198559397-0673cf4d-0031-4dc8-bd25-e5d384ab9d51.png)

**Comment by bjungs** [comment]
Hello Víctor,

Thank you for your submission.

I have not yet tested the plugin against the new platform version (223.*). I will do so as soon as I can and will update the version support.

Thanks again!

**Comment by bjungs** [comment]
I know you probably moved on already but, could you double check on you end? @victor-falcon 

![image](https://user-images.githubusercontent.com/16376552/204369862-bbcfa24a-5541-40fc-9b65-983163a44f51.png)

Thanks!
