### ISSUE TITLE
Encountered some problems after updating to IDEA 2024.x

### ISSUE THREAD

**Issue by JohnWickzzz** [youngstead/idea-relative-line-numbers#6]
Hi, After upgrade IDEA to 2024.1, the Absolute values may not work sometimes.
In the same project, some files are displayed and others are not, and cannot replicate stably.
Updated IDEA to 2024.2 today, and the issue still exists.

**Comment by bjungs** [comment]
Hello @JohnWickzzz, sorry for the late reply. I use this plugin every day and I never noticed any issues. I cannot replicate your experience. Does this still affect you?

Thanks!

**Comment by JohnWickzzz** [comment]
https://github.com/user-attachments/assets/040ef47b-acd1-4b5e-9dc6-7790d4ee1809

Hi, It's still affect me. Like screen recording, you can see it when IDEA starts, and then it disappears immediately.

IDEA version: 2024.2.3
MacOS: 15.0 / 12.7.3
I have 2 mac, they have similar issues.

**Comment by bjungs** [comment]
Hello @JohnWickzzz,

I don't have a mac but I tried it on Windows and Linux machines with the latest versions of IDEA, Webstorm, PyStorm, and RustRover and they all function as expected. 

I'm suspecting this might be a conflict with another plugin. Are you using any other plugins? Could you try disabling them? If that doesn't work, I would suggest you start from a fresh IDE install, or completely remove and re-install the plugin.

Also, can you confirm the status of the `Absolute values` setting?

If none of the above work, I'm afraid I cannot help you any further. Feel free to fork and contribute a solution if you find one. And please, _do_ let me know whether the issue persists or gets resolved. I appreciate your support.

**Comment by JohnWickzzz** [comment]
@bjungs  Oh, I found that it should be related to the IdeaVim plugin, but I haven't found a solution yet.

**Comment by bjungs** [comment]
@JohnWickzzz the IdeaVim plugin has its own line numbers solution.

I would advise you to simply uninstall this plugin if you are using IdeaVim.

**Comment by JohnWickzzz** [comment]
After several months, finally, I found the issue was caused of IdeaVim plugin in my mac. I don't know why IdeaVim in my IJ IDEA always stays in rnu status, so I set 'set norelativenumber' in ideavimrc, the problem is solved.
